# Generated by Django 4.2.1 on 2023-05-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('ad', models.CharField(blank=True, max_length=20, null=True)),
                ('soyad', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
    ]
